on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15'
      - name: Run Check
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: go run main.go check
      - name: Update history
        run: |
         git config --global user.email "jrgglt@gmail.com"
         git config --global user.name "jgalat"
         git add history.json 
         git commit -m "Update history" || true
         git push origin HEAD:master || true
